; PRÁCTICA 2
; ALITZEL GALILEA TORRES MACÍAS

		LIST 	P=16F887		; MICROCONTROLADOR A PROGRAMAR
		INCLUDE	"P16F887.INC"	; CARGA LA LIBRERÍA DEL MICROCONTROLADOR

		ORG 	0x00			; INICIO DE LA PRIMERA INSTRUCCIÓN
		GOTO 	INICIO			; VA A LA ETIQUETA "INICIO"

INICIO	BSF 		STATUS, RP0		; PONE EN 1 A RP0 PARA BANCO 3
		BSF 		STATUS, RP1		; PONE EN 1 A RP1 PARA BANCO 3
		CLRF 	TRISB			; PONE EN 0 A TRISB, DECLARA PUERTO B COMO SALIDA
		CLRF 	ANSEL			; PONE EN 0 A ANSEL
		CLRF 	ANSELH			; PONE EN 0 A ANSELH
		BCF 		STATUS, RP0		; PONE EN 0 A RP0 PARA BANCO 0
		BCF		STATUS, RP1		; PONE EN 0 A RP1 PARA BANCO 0

BUCLE	MOVF	PORTA, W		; MANDA LOS DATOS DEL PUERTO A AL REGISTRO W
		ADDWF	PORTA, W		; SUMA LOS DATOS DEL PUERTO A AL REGISTRO W
		ADDWF	PORTA, W		; SUMA LOS DATOS DEL PUERTO A AL REGISTRO W
		ADDWF	PORTA, W		; SUMA LOS DATOS DEL PUERTO A AL REGISTRO W
		ADDWF	PORTA, W		; SUMA LOS DATOS DEL PUERTO A AL REGISTRO W
		MOVWF	PORTB			; MANDA LOS DATOS DEL REGISTRO W AL PUERTO B
		GOTO	BUCLE			; VA A LA ETIQUETA "BUCLE"	

		END						; FIN DEL PROGRAMA